// <auto-generated />
using Backend.ChatEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations.Chat
{
    [DbContext(typeof(ChatContext))]
    partial class ChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Backend.ChatEntities.AuthTokenEntity", b =>
                {
                    b.Property<string>("AuthTokenGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("CookieString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAccessTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthTokenGuid");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("Backend.ChatEntities.ChatHistoryEntity", b =>
                {
                    b.Property<string>("UserGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserGuid");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("Grpc.Share.Protos.ChatModels.UserInfoModel", b =>
                {
                    b.Property<string>("UserGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailBox")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserGuid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Grpc.Share.Protos.ChatModels.VerifyCodeModel", b =>
                {
                    b.Property<string>("MailBox")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerifyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VerifyCodeType")
                        .HasColumnType("INTEGER");

                    b.HasKey("MailBox");

                    b.ToTable("VerifyCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
